<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-android</TargetFrameworks>
    <SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-android'))">34</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TetriON.Core\TetriON.Core.csproj" />
    <ProjectReference Include="..\TetriON.Shared\TetriON.Shared.csproj" />
    <ProjectReference Include="..\TetriON.Client.UI\TetriON.Client.UI.csproj" />
    <ProjectReference Include="..\TetriON.Client.Media\TetriON.Client.Media.csproj" />
    <ProjectReference Include="..\TetriON.Client.Audio\TetriON.Client.Audio.csproj" />
    <ProjectReference Include="..\TetriON.Client.Input\TetriON.Client.Input.csproj" />
    <ProjectReference Include="..\TetriON.Client.Particles\TetriON.Client.Particles.csproj" />
    <ProjectReference Include="..\TetriON.Client.Rendering\TetriON.Client.Rendering.csproj" />
    <ProjectReference Include="..\TetriON.Client.Networking\TetriON.Client.Networking.csproj" />
    <ProjectReference Include="..\TetriON.Client.Abstraction\TetriON.Client.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Extended" Version="5.3.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" Condition="'$(TargetFramework)' == 'net10.0'" />
        <PackageReference Include="MonoGame.Framework.Android" Version="3.8.*" Condition="'$(TargetFramework)' == 'net10.0-android'" />
  </ItemGroup>

</Project>
