<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TetriON.Client.Abstraction\TetriON.Client.Abstraction.csproj" />
        <ProjectReference Include="..\TetriON.Client.Media\TetriON.Client.Media.csproj" />
        <ProjectReference Include="..\TetriON.Shared\TetriON.Shared.csproj" />
    </ItemGroup>
</Project>
